### ISSUE TITLE
Zowe Quarterly Webinar

### ISSUE THREAD

**Issue by RASakach** [zowe/community#2223]
The next Quarterly Update Webinar

Mid-May Target  4/22 or 4/29 at 11:30 ET

Topics for consideration:

- Zowe Clients TEAM CONFIGURATION
- ZWE - JCL  (wait until released)
- State of Zowe releases, Zowe v1 EOS, Zowe v2 Maintenance, Zowe v3, Converting to Team Configuration / Global & Local configuration files (Enterprise Team configuration) - include a mention of SHARE and encourage customers to attend

**Comment by RASakach** [comment]
@adam-wolfe , @JillieBeanSim :  We are looking for a Community member or members to present at the Quarterly Update webinar tentatively scheduled for 5/29 at 11:30 ET

Can you let us know who will present and if they are available at the specified date/time?

Topic:  Zowe Clients Team Configuration
(Proposed) Abstract:  With Zowe v3 on the release horizon , Team Config for Zowe CLI and Zowe Explorer for VS Code becomes more relevant than ever.  In Zowe v1, user profiles were required for EVERY user.  Zowe v2 introduced Team Config to take the burden of learning, understanding, and implementing connectivity away from the majority of end users.  Zowe v3 mandates the use of Team Config. Join this session for a comprehensive review of Team Config, what it looks like, how best to leverage it, and best practices for  converting Zowe CLI v1 profiles to Team Config to ensure you and your team are ready for Zowe v3!

**Comment by adam-wolfe** [comment]
Hi @RASakach, @JillieBeanSim and I discussed this and agreed that I would present.

**Comment by RASakach** [comment]
@adam-wolfe & @JillieBeanSim Fantastic.  TY - I will send this information out to Mae and get it scheduled.   

@JillieBeanSim please let me know if you or anyone else on the team would like to be added to the "host" list to help respond to questions.

**Comment by RASakach** [comment]
@RASakach will open an issue in the DOC repo to request the details be added to the DOC:  Zowe Announcements area

Include:  Date / Time / Registration Link
Include:  blurb about the topic and why folks should attend
Include:  When to post / when to remove

**Comment by RASakach** [comment]
Registration link:  https://zoom.platform.linuxfoundation.org/webinar/register?project=open-mainframe-project&id=EKG%2BnTfz7Kipp1okh7gFsT4rUklFurpMmu6mzHsu0L%2Bc75tfIxCJjQ%3D%3D&logo=openmainframeproject-color.svg&zoomID=93379855157


Webinar details:
Join the Zowe community on Wednesday, May 29 at 11:30 am -12:30 pm ET for the next quarterly update! Register [here](https://zoom.platform.linuxfoundation.org/webinar/register?project=open-mainframe-project&id=EKG%2BnTfz7Kipp1okh7gFsT4rUklFurpMmu6mzHsu0L%2Bc75tfIxCJjQ%3D%3D&logo=openmainframeproject-color.svg&zoomID=93379855157). 

With Zowe v3 on the release horizon, Team Config for Zowe CLI and Zowe Explorer for VS Code becomes more relevant than ever. The Zowe Community introduced Team Config to take the burden of learning, understanding, and implementing connectivity away from every user – which is what v1 profiles required.

Join this session for a comprehensive review of Team Config, what it looks like, how best to leverage it, and (for those of you still using v1 profiles) best practices for converting Zowe CLI v1 profiles to Team Config to ensure you and your team are ready for Zowe v3!

Speaker: Adan Wolfe, Product Owner at Broadcom and Open Mainframe Project Ambassador

Register [here](https://zoom.platform.linuxfoundation.org/webinar/register?project=open-mainframe-project&id=EKG%2BnTfz7Kipp1okh7gFsT4rUklFurpMmu6mzHsu0L%2Bc75tfIxCJjQ%3D%3D&logo=openmainframeproject-color.svg&zoomID=93379855157).

```[tasklist]
### Tasks
- [ ] Update zowe.org announcements
- [ ] update zowe SLACK announcements
- [ ] promote via LinkedIn
- [ ] promote via email distribution lists
- [ ] promote via DISCORD
- [ ] promote via IBM Champion channels
```

**Comment by JillieBeanSim** [comment]
> @adam-wolfe & @JillieBeanSim Fantastic. TY - I will send this information out to Mae and get it scheduled.
> 
> @JillieBeanSim please let me know if you or anyone else on the team would like to be added to the "host" list to help respond to questions.

Hey @RASakach can you add myself and @t1m0thyj as host to help answer questions? Thanks

**Comment by RASakach** [comment]
@JillieBeanSim and @t1m0thyj :  I've asked Mae to add you to the speaker list.  Please keep an eye out for the meeting invitation and your personal speaker link.

@anaxceron I have opened a DOC issue to add the Webinar information to Zowe Docs Announcements:  https://github.com/zowe/docs-site/issues/3647
